services:
  alarm-server:
    build: .
    ports:
      - "6033:6033"
    environment:
      - PAGERDUTY_API_TOKEN=${PAGERDUTY_API_TOKEN}
      - PAGERDUTY_SERVICE_ID=${PAGERDUTY_SERVICE_ID}
      - PAGERDUTY_FROM_EMAIL=${PAGERDUTY_FROM_EMAIL}
      - PAGERDUTY_ALERT_TYPES=${PAGERDUTY_ALERT_TYPES}
      - PAGING_START_TIME=${PAGING_START_TIME:-00:00}
      - PAGING_END_TIME=${PAGING_END_TIME:-23:59}
    restart: unless-stopped
